miner.client.delayBetweenBlocks = 3 second
rpc {
    providers {
        web {
            cors: "*"
            http {
                enabled = true
                bind_address = "0.0.0.0"
                hosts = ["localhost", "127.0.0.1", "::1", "l1", "host.docker.internal"],
                port = 4444
            }
            ws {
                enabled = true
                bind_address = "0.0.0.0"
                port = 4445
            }
        }
    }
}

hello.phrase = "Hello from RegTest"

genesis = "/etc/rsk/genesis/rsk-dev.json"
