# blockchain.config {
#     name = regtest
#     hardforkActivationHeights = {
#         bahamas = 0,
#         afterBridgeSync = -1,
#         orchid = 0,
#         orchid060 = 0,
#         wasabi100 = 0,
#         twoToThree = 0,
#         papyrus200 = 0,
#         iris300 = 0,
#         hop400 = 0,
#         hop401 = 0,
#         fingerroot500 = 0,
#         arrowhead600 = 0,
#         arrowhead631 = -1,
#         lovell700 = 0,
#         reed800 = 0,
#         reed810 = 0,
#         vetiver900 = 0
#     },
#     consensusRules = {
#         rskip97 = -1 # disable orchid difficulty drop
#         rskipUMM = 1
#         rskip144 = 1
#         rskip351 = 1
#     }
# }

# peer {
#     discovery = {
#         # if peer discovery is off
#         # the peer window will show
#         # only what retrieved by active
#         # peer [true/false]
#         enabled = false

#         # List of the peers to start
#         # the search of the online peers
#         # values: [ip:port]
#         ip.list = [ ]
#     }

#     # Port for server to listen for incoming connections
#     port = 50501

#     # Network id
#     networkId = 7771
# }

# miner {
#     server.enabled = true

#     client {
#         enabled = true
#         delayBetweenBlocks = 3 second
#     }

#     # this is a secret passphrase that is used to derive the address where the miner gets the reward.
#     # please note this is stored in a local wallet and not recommended for production.
#     coinbase.secret = regtest_miner_secret_please_change
# }

# database {
#     # place to save physical storage files
#     dir = ${user.home}/.rsk/regtest/database
# }

# # account loaded when the node start.
# wallet {
#     accounts = [{ privateKey = "d10f0f2609f060955fe5d38edf88010abd4b983374ce4f898caf3bb7485db1e7" }]
#     enabled = true
# }

miner.server.enabled = true
miner.client.enabled = true
miner.client.delayBetweenBlocks = 3 second
miner.coinbase.secret = regtest_miner_secret_please_change

rpc.providers.web {
  cors: "*"
  http {
      enabled = true
      bind_address = "0.0.0.0"
      # hosts = ["localhost", "127.0.0.1", "::1", "l1", "host.docker.internal"],
      hosts = ["*"],
      port = 4444
  }
  ws {
      enabled = true
      bind_address = "0.0.0.0"
      port = 4445
  }
}

hello.phrase = "Choo choo!"

# genesis = "/etc/rsk/genesis/rsk-dev.json"
